version: '3.4'

services:
  proxy:
    image: traefik
    command: --api --docker --docker.swarmmode --docker.watch --docker.domain=swarm.mraz.org --logLevel=DEBUG
    networks:
      - consul
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager


networks:
  consul:
    external: true
