################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "swarm.mraz.org"
watch = true
# exposedbydefault = false
