version: '3.1'

services:
  minio1:
    image: minio/minio:latest
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - minion
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:latest
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minion
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:latest
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minion
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:latest
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minion
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  haproxy:
    image: eeacms/haproxy
    ports:
    - "80:5000"
    - "1936:1936"
    networks:
      - minion
    environment:
      BACKENDS: "minio1:9000 minio2:9000 minio3:9000 minio4:9000"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

  bb:
    image: library/busybox
    networks:
      - minion
    command:
      - "sleep"
      - "30000"

volumes:
  minio1-data:

  minio2-data:

  minio3-data:

  minio4-data:

networks:
  minion:
    external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true
