version: '3.1'

services:
  minio:
    image: 127.0.0.1:5000/minio:latest
    volumes:
      - /export
    ports:
      - "9000:9000"
    networks:
      - minion
    environment:
      - REPLICAS=4
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    secrets:
      - secret_key
      - access_key

networks:
  minion:
    external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true
